"""Audio in → STT → LLM (+ tools) → TTS."""
from __future__ import annotations

import asyncio
import json
import logging
import time
from functools import lru_cache
from typing import AsyncIterator

from ..capabilities import SPEECH_LLM_TOOLASSIST_SPEECH
from ..guardrails import report
from ..languages import base_code, english_name
from ..profiles import get_profile
from ..session import VoiceSession
from ..tracing import TurnTrace, submit_trace
from . import ServingBundle
from ._shared import language_mismatch, resolve_language, stream_tts, transcribe

logger = logging.getLogger("realtime_voice")

@lru_cache(maxsize=1)
def _llm_turn_timeout_s() -> float:
    """Config-sourced LLM per-turn budget (realtime_voice.timeouts.llm_turn_s).

    Covers cold-start + multi-tool-iteration loops; generous enough for the tool
    rounds but tight enough that a hung endpoint doesn't strand the caller. Cached
    (config is static per process); falls back to the dataclass default on error.
    """
    try:
        from ..config import RealtimeSettings

        return float(RealtimeSettings.resolve().llm_turn_timeout_s)
    except Exception:  # noqa: BLE001
        return 50.0

# How long to wait for the LLM before playing a spoken acknowledgment. Fast
# turns (cached / no tool calls) return well under this, so they stay snappy and
# never hear a filler. Slower turns (Lakebase + Genie tool rounds) cross it and
# the caller hears a natural "let me check" instead of dead air.
_FILLER_GRACE_S = 0.6

# Voice-first spoken moments (filler acknowledgment + "switch language" prompt)
# are generated by the multilingual model in the *selected* language and cached
# per language — no hardcoded per-language phrase tables and no English fallback,
# so they render correctly for every supported language. Filler is warmed in the
# background the first time a language is used, so no turn blocks on generating it.
_FILLER_CACHE: dict[str, str] = {}
_FILLER_WARMING: set[str] = set()
_SWITCH_CACHE: dict[str, str] = {}

_FILLER_INTENT = (
    "Politely acknowledge that you are looking into the customer's request right "
    "now, and ask them to hold on for just a moment."
)


def _switch_intent(detected: str) -> str:
    name = english_name(detected)
    return (
        f"You noticed the caller is speaking {name}, but the app is currently set "
        f"to a different language. In one short sentence, tell them you heard {name} "
        f"and ask them to switch the app's language to {name} so you can continue."
    )


async def warm_filler(bundle: ServingBundle, language: str) -> None:
    """Public entrypoint to pre-generate the in-language filler (see _warm_filler).

    Called at session start so the acknowledgment is cached and ready before the
    first (often cold, tool-heavy) turn finishes — otherwise turn 1 races LLM
    generation against the grace window and the caller hears dead air.
    """
    await _warm_filler(bundle, language)


async def _warm_filler(bundle: ServingBundle, language: str) -> None:
    """Generate + cache the in-language filler once per language (background)."""
    # No concrete language yet ("auto") → nothing to warm; the per-turn warm fires
    # once STT resolves the actual language. Guarding here keeps a stray "auto"
    # from caching an English clip under a bogus key.
    if not language or language == "auto":
        return
    base = base_code(language)
    if base in _FILLER_CACHE or base in _FILLER_WARMING:
        return
    _FILLER_WARMING.add(base)
    try:
        text = (await asyncio.to_thread(bundle.llm.phrase, _FILLER_INTENT, language=language)).strip()
        if text:
            _FILLER_CACHE[base] = text
    except Exception:  # noqa: BLE001
        logger.warning("filler generation failed for %s", language, exc_info=True)
    finally:
        _FILLER_WARMING.discard(base)


# Spoken confirmations for deterministically-resolved intents (e.g. the home
# concierge's "taking you to <industry> now") are generated in the caller's
# language and cached per (intent, base-language) — one model call per phrase.
_CONFIRM_CACHE: dict[tuple[str, str], str] = {}


async def _confirm_phrase(bundle: ServingBundle, intent: str, language: str) -> str:
    """Short spoken confirmation for a pre-routed intent, in the caller's language."""
    key = (intent, base_code(language))
    cached = _CONFIRM_CACHE.get(key)
    if cached is not None:
        return cached
    try:
        text = (await asyncio.to_thread(bundle.llm.phrase, intent, language=language)).strip()
    except Exception:  # noqa: BLE001
        logger.warning("confirmation phrase generation failed for %s", language, exc_info=True)
        text = ""
    if text:
        _CONFIRM_CACHE[key] = text
    return text


async def _switch_prompt(bundle: ServingBundle, expected: str, detected: str) -> str:
    """Spoken 'wrong language' prompt, rendered in the agent's selected language."""
    key = f"{base_code(expected)}>{base_code(detected)}"
    cached = _SWITCH_CACHE.get(key)
    if cached is not None:
        return cached
    text = (await asyncio.to_thread(bundle.llm.phrase, _switch_intent(detected), language=expected)).strip()
    if text:
        _SWITCH_CACHE[key] = text
    return text


async def process_turn(
    bundle: ServingBundle,
    session: VoiceSession,
    turn_id: int,
    audio: bytes,
    *,
    context: str | None = None,
) -> AsyncIterator[dict]:
    # One trace per turn: STT → language gate → LLM (+tool) iterations → TTS. The
    # trace is submitted to a background writer in the finally block, so it is
    # persisted even on early-return paths (empty/mismatch/superseded) and errors,
    # and NEVER blocks the turn (submit is a non-blocking enqueue).
    trace = TurnTrace(
        session_id=session.session_id or "",
        turn_id=turn_id,
        capability=SPEECH_LLM_TOOLASSIST_SPEECH,
        call_id=session.config.call_id,
        customer_id=session.config.customer_id,
    )
    trace.language = session.config.language
    try:
        stt_span = trace.span(
            "stt", "STT",
            input={
                "audio_bytes": len(audio),
                "sample_rate_hz": session.config.sample_rate_hz,
                "requested_language": session.config.language,
                "expected_language": session.config.expected_language,
            },
        )
        transcript, detected, stt_ms = await transcribe(bundle, session, audio)
        stt_span.set_output({"transcript": transcript, "detected_language": detected}).set_attribute(
            "stt_ms", stt_ms
        ).end()
        trace.input_transcript = transcript
        trace.detected_language = detected
        # Log EVERY STT result (including empties) so silent-drop turns are visible:
        # distinguishes "STT heard nothing" (silence/echo) from "STT heard the wrong
        # language" (gate) from a real transcript.
        logger.info(
            "stt turn %d: %dms detected=%s len=%d text=%r",
            turn_id, stt_ms, detected, len(transcript), transcript[:120],
        )
        # Group B: what Qwen3-ASR owns for us. Recorded honestly — "delegated" only
        # when its language ID actually ran, which it does not when the session
        # pinned a language (then `detected` merely echoes our own choice).
        pinned = bool(session.config.language) and session.config.language != "auto"
        report(
            trace.guards, "language_id",
            "not_evaluated" if pinned else "delegated",
            stage="stt", owner="qwen",
            reason=(
                f"session pinned language={session.config.language}"
                if pinned
                else f"detected_language={detected or 'unknown'}"
            ),
        )
        report(
            trace.guards, "no_speech_suppression",
            "fired" if not transcript.strip() else "passed",
            stage="stt", owner="qwen",
            reason="empty transcript from STT" if not transcript.strip() else None,
        )

        if turn_id != session.turn_id:
            trace.status = "superseded"
            report(
                trace.guards, "stale_turn", "fired",
                stage="turn", surface="internal",
                reason=f"turn {turn_id} superseded by {session.turn_id}",
            )
            return
        if not transcript.strip():
            trace.status = "empty_transcript"
            report(
                trace.guards, "empty_transcript", "fired",
                stage="turn", surface="internal", reason="blank transcript; turn dropped",
            )
            return
        # Language gate: if the caller isn't speaking the selected language, don't
        # surface the off-language transcript or run the assistant. Warn the UI
        # (visual banner) and *speak* a localized prompt asking the agent to switch
        # the picker — the spoken guidance lives here because this is the only route
        # with a TTS stage. The turn is otherwise dropped (no history, no LLM/reply).
        mismatch = language_mismatch(session, detected)
        if not session.config.expected_language:
            report(
                trace.guards, "language_gate", "not_evaluated",
                seam="decision", stage="routing",
                reason="session set no expected_language",
            )
        else:
            report(
                trace.guards, "language_gate", "fired" if mismatch else "passed",
                seam="decision", stage="routing",
                reason=(
                    f"expected={mismatch['expected']} detected={mismatch['detected']}; "
                    "turn dropped, switch prompt spoken"
                    if mismatch
                    else f"detected={detected or 'unknown'} matches selection"
                ),
            )
        if mismatch:
            trace.status = "language_mismatch"
            with trace.span("language.gate", "GUARD", input={"detected": detected}) as gate:
                gate.set_output(mismatch)
            yield {"type": "language.mismatch", "turn_id": turn_id, **mismatch}
            try:
                prompt = await _switch_prompt(bundle, mismatch["expected"], mismatch["detected"])
            except Exception:  # noqa: BLE001
                logger.warning("switch-language phrase failed for turn %d", turn_id, exc_info=True)
                prompt = ""
            if prompt:
                try:
                    async for event in stream_tts(
                        bundle, session, turn_id, prompt, mismatch["expected"],
                        emit_text=False, trace=trace,
                    ):
                        if turn_id != session.turn_id:
                            break
                        yield event
                except Exception:  # noqa: BLE001
                    logger.warning("switch-language TTS failed for turn %d", turn_id, exc_info=True)
            session.set_cooldown(1.5)
            return

        language = resolve_language(session, detected)
        trace.language = language
        # Warm the in-language filler in the background so a later slow turn in this
        # language can play it without blocking on generation.
        asyncio.ensure_future(_warm_filler(bundle, language))
        yield {
            "type": "transcript.final",
            "turn_id": turn_id,
            "text": transcript,
            "language": language,
            "stt_ms": stt_ms,
        }

        session.history.append({"role": "user", "content": transcript})

        # Every session runs through a named profile (see profiles.py). Defaults
        # to "billing" (the original telco contact-center behavior) when the
        # frontend doesn't specify one.
        profile = get_profile(session.config.profile or "billing")
        tool_ctx = profile.make_context(session, language)

        # ── Deterministic intent pre-router (framework seam) ──────────────
        # Navigation/selection is a DETERMINISTIC action; don't gate it solely
        # on the conversational LLM choosing to emit the tool call. If the
        # profile resolves a confident intent from this transcript, run it via
        # the same tool_runner (so the usual tool.called event fires), speak a
        # short in-language confirmation, and SKIP the LLM turn. Ambiguous / no
        # match returns [] and falls through to the LLM below, which can clarify
        # and still call the tool itself. Fully generic: the engine never names
        # a domain — only the profile knows what its intents are.
        resolver = getattr(profile, "resolve_intents", None)
        resolved = resolver(transcript, language, trace.guards) if resolver is not None else []
        if resolved:
            with trace.span("intent.router", "GUARD", input={"transcript": transcript}) as span:
                span.set_output({"intents": [r.name for r in resolved]})
            confirm_text = ""
            for r in resolved:
                try:
                    result_json = profile.tool_runner(r.name, r.arguments, tool_ctx)
                except Exception:  # noqa: BLE001
                    logger.warning("intent-router tool %s failed for turn %d", r.name, turn_id, exc_info=True)
                    continue
                try:
                    result_obj = json.loads(result_json)
                except (TypeError, ValueError):
                    result_obj = result_json
                yield {
                    "type": "tool.called",
                    "turn_id": turn_id,
                    "name": r.name,
                    "arguments": r.arguments,
                    "result": result_obj,
                }
                if r.confirm_intent and not confirm_text:
                    confirm_text = await _confirm_phrase(bundle, r.confirm_intent, language)
            if turn_id != session.turn_id:
                trace.status = "superseded"
                return
            if confirm_text:
                session.history.append({"role": "assistant", "content": confirm_text})
                trace.output_text = confirm_text
                yield {"type": "response.text", "turn_id": turn_id, "text": confirm_text}
                tts_span = trace.span("tts", "TTS", input={"text": confirm_text, "language": language})
                async for event in stream_tts(
                    bundle, session, turn_id, confirm_text, language, trace=trace
                ):
                    if turn_id != session.turn_id:
                        break
                    yield event
                tts_span.set_attribute("tts_first_ms", trace.tts_first_ms).end()
            if profile.after_turn is not None:
                profile.after_turn(tool_ctx, session)
            session.set_cooldown(1.5)
            return

        respond_extra: dict = {
            "system_prompt": profile.system_prompt,
            "tools_override": profile.tools_spec(),
            "tool_runner": profile.tool_runner,
        }
        t = time.perf_counter()
        respond_fn = getattr(bundle.llm, "respond_with_tools", None)
        tool_invocations: list[dict] = []

        # Snapshot the history the LLM will actually see this turn (text-only —
        # tool calls are NOT persisted across turns). This is the single most
        # useful field for diagnosing why a confirmation turn re-confirms instead
        # of applying: you can read exactly what context the model had.
        history_for_turn = [dict(m) for m in session.history[:-1]]
        trace.span("history", "GUARD", input={"messages": history_for_turn}).set_output(
            {"message_count": len(history_for_turn)}
        ).end()

        # Run the LLM (+tools) as a background task so we can cover its latency with a
        # spoken acknowledgment. The task keeps running while we stream the filler.
        if respond_fn:
            llm_task = asyncio.ensure_future(
                asyncio.to_thread(
                    respond_fn, transcript, language=language, context=context,
                    tool_ctx=tool_ctx, history=session.history[:-1], trace=trace,
                    **respond_extra,
                )
            )
        else:
            llm_task = asyncio.ensure_future(
                asyncio.to_thread(
                    bundle.llm.respond, transcript, language=language, context=context, tool_ctx=tool_ctx
                )
            )

        try:
            await asyncio.wait({llm_task}, timeout=_FILLER_GRACE_S)
            if not llm_task.done():
                filler = _FILLER_CACHE.get(base_code(language))
                if filler:
                    # Spanned separately from the answer's TTS: the filler is what
                    # ends the caller's silence, so the waterfall has to show it or
                    # ttft looks like it came from nowhere.
                    filler_span = trace.span(
                        "tts.filler", "TTS", input={"text": filler, "language": language}
                    )
                    try:
                        async for event in stream_tts(
                            bundle, session, turn_id, filler, language,
                            mark_final=False, emit_text=False, trace=trace, primary=False,
                        ):
                            if turn_id != session.turn_id:
                                break
                            yield event
                    except Exception:  # noqa: BLE001
                        logger.warning("filler TTS failed for turn %d", turn_id, exc_info=True)
                        filler_span.set_status("error")
                    filler_span.end()

            if turn_id != session.turn_id:
                llm_task.cancel()
                trace.status = "superseded"
                return

            llm_timeout = _llm_turn_timeout_s()
            remaining = max(1.0, llm_timeout - (time.perf_counter() - t))
            try:
                result = await asyncio.wait_for(asyncio.shield(llm_task), timeout=remaining)
            except asyncio.TimeoutError:
                logger.error("LLM timed out after %ss for turn %d", llm_timeout, turn_id)
                raise RuntimeError(f"LLM response timed out after {llm_timeout}s") from None
        finally:
            if llm_task.done() and not llm_task.cancelled():
                llm_task.exception()  # retrieve to avoid "exception never retrieved"
            else:
                llm_task.cancel()

        if respond_fn:
            response_text, tool_invocations = result
        else:
            response_text = result
        llm_ms = round((time.perf_counter() - t) * 1000)
        trace.output_text = response_text
        logger.info("LLM responded in %dms (turn %d, tools=%d)", llm_ms, turn_id, len(tool_invocations))
        if turn_id != session.turn_id:
            trace.status = "superseded"
            return

        session.history.append({"role": "assistant", "content": response_text})
        # Keep history bounded to last 10 exchanges (20 messages)
        if len(session.history) > 20:
            session.history = session.history[-20:]

        for invocation in tool_invocations:
            yield {
                "type": "tool.called",
                "turn_id": turn_id,
                "name": invocation["name"],
                "arguments": invocation.get("arguments"),
                "result": invocation.get("result"),
            }

        yield {
            "type": "response.text",
            "turn_id": turn_id,
            "text": response_text,
            "llm_ms": llm_ms,
        }

        # Let the profile persist any small cross-turn state (e.g. a selected use
        # case) onto session.profile_state. Generic: the engine doesn't know or
        # care what a given profile stores.
        if profile.after_turn is not None:
            profile.after_turn(tool_ctx, session)

        # The span's duration_ms is the FULL synthesis+stream (blocking) time.
        # tts_first_ms is this synthesis' own time-to-first-audio; the turn-level
        # figure the caller actually felt is trace.ttft_ms, which may belong to a
        # filler that played earlier.
        tts_span = trace.span("tts", "TTS", input={"text": response_text, "language": language})
        tts_chunks = 0
        tts_first_ms: int | None = None
        async for event in stream_tts(
            bundle, session, turn_id, response_text, language, trace=trace
        ):
            if event.get("type") == "response.audio":
                tts_chunks += 1
                if tts_first_ms is None and event.get("tts_first_ms") is not None:
                    tts_first_ms = event.get("tts_first_ms")
                    tts_span.set_attribute("tts_first_ms", tts_first_ms)
            yield event
        tts_span.set_output({"chunks": tts_chunks, "tts_first_ms": tts_first_ms}).end()

        # After TTS completes, suppress turn finalization for 1.5s to prevent
        # speaker→mic echo from immediately triggering a false follow-up turn.
        session.set_cooldown(1.5)
    except asyncio.CancelledError:
        trace.status = "cancelled"
        raise
    except Exception as exc:  # noqa: BLE001
        trace.status = "error"
        trace.error = repr(exc)
        raise
    finally:
        submit_trace(trace)
